name: Build LDC with PGO instrumentation & gather profile from compiling default libs
inputs:
  cmake_flags:
    required: false
    default: ''
  arch:
    required: false # Windows only
runs:
  using: composite
  steps:

    - name: Build LDC with PGO instrumentation & gather profiles from compiling default libs
      uses: ./.github/actions/helper-build-ldc
      with:
        build_dir: pgo-ldc
        host_dc: ../bootstrap-ldc/bin/ldmd2
        # we need to escape `%p` as `%%p` on Windows (batch shell)
        cmake_flags: >-
          -DBUILD_SHARED_LIBS=OFF
          "-DDFLAGS_LDC=-fprofile-generate=${{ runner.os == 'Windows' && '%CD%\%%p' || '$PWD/%p' }}.profraw"
          ${{ inputs.cmake_flags }}
        arch: ${{ inputs.arch }}

    - name: Merge PGO profiles # to ../pgo-ldc/merged.profdata
      shell: bash
      run: |
        set -eux
        cd ../pgo-ldc
        ../bootstrap-ldc/bin/ldc-profdata merge --output=merged.profdata *.profraw
        ls -lh *.prof{data,raw}
