#---------------------------------#
#      general configuration      #
#---------------------------------#

#version: 1.0.{build}-{branch}

branches:
  only:
    - appveyor

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - '"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - msbuild /version
  - cl
  - cmake --version
  - python --version

# fetch repository as zip archive
shallow_clone: true

# scripts that run after cloning repository
install:
  - cd c:\projects
  # Clone libconfig
  - git clone https://github.com/hyperrealm/libconfig.git libconfig
  # Download and extract LLVM source
  - ps: (new-object net.webclient).DownloadFile('http://llvm.org/pre-releases/3.7.0/rc3/llvm-3.7.0rc3.src.tar.xz', 'c:/projects/llvm.src.tar.xz')
  - 7z x llvm.src.tar.xz -so | 7z x -si -ttar > nul
  - ren llvm-3.7.0rc3.src llvm
  # Download and install Ninja
  - ps: (new-object net.webclient).DownloadFile('https://github.com/martine/ninja/releases/download/v1.6.0/ninja-win.zip', 'c:/projects/ninja.zip')
  - md ninja
  - cd ninja
  - 7z x ..\ninja.zip
  - set PATH=c:\projects\ninja;%PATH%
  - cd ..
  - ninja --version

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - cd c:\projects
  # Build libconfig
  - msbuild libconfig\lib\libconfig.vcxproj /p:Configuration=ReleaseStatic /p:Platform=x64
  # Generate build files for LLVM and build & install
  - md ninja-llvm
  - cd ninja-llvm
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=c:\projects\llvm-x64 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_APPEND_VC_REV=ON ..\llvm
  - ninja install

build_script:
  - cd c:\projects
  # Generate build files for LDC and build
  - md ninja-ldc
  - cd ninja-ldc
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ROOT_DIR=c:/projects/llvm-x64 -DLIBCONFIG_INCLUDE_DIR=c:/projects/libconfig/lib -DLIBCONFIG_LIBRARY=c:/projects/libconfig/lib/x64/ReleaseStatic/libconfig.lib ..\ldc
  - ninja all

after_build:

#---------------------------------#
#       test configuration        #
#---------------------------------#

before_test:

test_script:

after_test:
