#---------------------------------#
#      general configuration      #
#---------------------------------#

#version: 1.0.{build}-{branch}

branches:
  only:
    - appveyor

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
#os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - msbuild /version
  - python --version

clone_folder: c:\projects\ldc

# fetch repository as zip archive
shallow_clone: true

# scripts that run after cloning repository
install:
  - cd c:\projects
  # Clone libconfig
  - git clone https://github.com/hyperrealm/libconfig.git libconfig
  # Download CMake and LLVM
  - md downloads
  - ps: (new-object net.webclient).DownloadFile('http://www.cmake.org/files/v3.3/cmake-3.3.1-win32-x86.zip', 'c:/projects/downloads/cmake.zip')
  - ps: (new-object net.webclient).DownloadFile('http://llvm.org/releases/3.6.2/LLVM-3.6.2-win32.exe', 'c:/projects/downloads/llvm.exe')
  # Install CMake
  - 7z x downloads\cmake.zip
  - set PATH=c:\projects\cmake\bin;%PATH%
  - cmake --version
  # Install LLVM
  - downloads\llvm.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - cd c:\projects
  # Generate msbuild files for LDC
  - md msbuild-ldc
  - cd msbuild-ldc
  - cmake -G "Visual Studio 2013 x64" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLIBCONFIG_INCLUDE_DIR=c:/projects/libconfig/lib -DLIBCONFIG_LIBRARY=c:/projects/libconfig/lib/x64/ReleaseStatic/libconfig.lib ..\ldc

build_script:
  - cd c:\projects
  # Build libconfig
  - msbuild libconfig\lib\libconfig.vcxproj /p:Configuration=ReleaseStatic /p:Platform=x64
  # Build LDC
  - msbuild msbuild-ldc\ALL_BUILD.vcxproj

after_build:

#---------------------------------#
#       test configuration        #
#---------------------------------#

before_test:

test_script:

after_test:
