jobs:
- job: Windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    LLVM_VERSION: 7.0.1
    CLANG_VERSION: 7.0.1
    HOST_LDC_VERSION: 1.13.0
    VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
    EXTRA_CMAKE_FLAGS: -DBUILD_LTO_LIBS=ON
  strategy:
    matrix:
      x64:
        OS: win64
        MODEL: 64
        ARCH: x64
      x86:
        OS: win32
        MODEL: 32
        ARCH: x86
        CFLAGS: -m32
        CXXFLAGS: -m32
        ASMFLAGS: -m32
  steps:
    - template: .azure-pipelines/windows.yml

- job: Windows_multilib
  timeoutInMinutes: 30
  pool:
    vmImage: 'vs2017-win2016'
  dependsOn:
    - Windows
  steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'windows-x64'
        targetPath: 'artifacts'
      displayName: Download x64 artifact
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'windows-x86'
        targetPath: 'artifacts'
      displayName: Download x86 artifact
    - script: |
        if "%BUILD_SOURCEBRANCH:~0,10%" == "refs/tags/" (
          set ARTIFACT_ID=%BUILD_SOURCEBRANCH:~10%
        ) else (
          set ARTIFACT_ID=%BUILD_SOURCEVERSION:~0,8%
        )
        set ARTIFACT_NAME=ldc2-%ARTIFACT_ID%-windows-multilib
        echo ##vso[task.setvariable variable=ARTIFACT_NAME]%ARTIFACT_NAME%
        7z x artifacts/ldc2-*-x64.7z > nul
        7z x artifacts/ldc2-*-x86.7z > nul
        mv ldc2-*-x64 %ARTIFACT_NAME%
        cd %ARTIFACT_NAME%
        mv lib lib64
        cp -r ../ldc2-*-x86/lib .
        mv lib lib32
      displayName: Extract & merge artifacts
    - powershell: |
        cd ldc2-*-multilib
        (cat etc\ldc2.conf).replace('%%ldcbinarypath%%/../lib', '%%ldcbinarypath%%/../lib64') | Set-Content etc\ldc2.conf
        $conf32 = cat ..\ldc2-*-x86\etc\ldc2.conf -Raw
        $conf32 = "`r`n""i[3-6]86-.*-windows-msvc"":" + $conf32.Substring($conf32.IndexOf("`r`ndefault:") + 10)
        $conf32 = $conf32.Substring(0, $conf32.IndexOf("`r`n};`r`n") + 6)
        $conf32 = $conf32.Replace('%%ldcbinarypath%%/../lib', '%%ldcbinarypath%%/../lib32')
        Add-Content etc\ldc2.conf $conf32
        cat etc\ldc2.conf
      displayName: Merge ldc2.conf
    - script: |
        mkdir newArtifacts
        7z a -mx=9 newArtifacts/%ARTIFACT_NAME%.7z %ARTIFACT_NAME% > nul
      displayName: Pack
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'windows-multilib'
        targetPath: 'newArtifacts'
      displayName: Publish artifact
