name: 3-build-cross
inputs:
  arch:
    required: true
  os:
    required: true
  llvm_version:
    required: true
  android_ndk_version:
    required: false
    default: r21e
  android_api_level:
    required: false
    default: 21
runs:
  using: composite
  steps:

    - name: Download & extract LDC-flavoured LLVM for ${{ inputs.os }}/${{ inputs.arch }} target # into ../llvm-cross
      shell: bash
      run: |
        set -eux
        cd ..
        version='${{ inputs.llvm_version }}'
        if [[ "$version" = *.* ]]; then
          tag="ldc-v$version"
        else
          tag=CI
        fi
        curl -fL --retry 3 --max-time 300 -o llvm-cross.tar.xz \
          "https://github.com/ldc-developers/llvm-project/releases/download/$tag/llvm-$version-${{ inputs.os }}-${{ inputs.arch }}.tar.xz"
        mkdir llvm-cross
        tar -xf llvm-cross.tar.xz --strip 1 -C llvm-cross
        rm llvm-cross.tar.xz

    - name: Make non-native llvm-config runnable on host
      shell: bash
      run: |
        set -eux
        cd ..
        if [[ '${{ inputs.os }}' == android ]]; then
          # Android: use a bash script template
          version="$(llvm/bin/llvm-config --version)" # from native LLVM
          sed ldc/.azure-pipelines/android-llvm-config.in \
            -e "s|@LLVM_VERSION@|$version|g" \
            -e "s|@LLVM_INSTALL_DIR@|$PWD/llvm-cross|g" \
            -e "s|@LLVM_DEFAULT_TARGET_TRIPLE@|irrelevant-android-triple|g" \
            -e "s|@LLVM_TARGETS@|AArch64 ARM X86 WebAssembly|g" \
            > llvm-cross/bin/llvm-config
          chmod 755 llvm-cross/bin/llvm-config
        else
          echo TODO
          exit 1
        fi

    - name: 'Android: Download & extract NDK; set DFLAGS, CROSS_TRIPLE & CROSS_CMAKE_FLAGS'
      if: inputs.os == 'android'
      shell: bash
      run: |
        set -eux
        cd ..
        version='${{ inputs.android_ndk_version }}'
        curl -fL --retry 3 --max-time 300 -o android-ndk.zip \
          "https://dl.google.com/android/repository/android-ndk-$version-linux-x86_64.zip"
        unzip android-ndk.zip >/dev/null
        mv "android-ndk-$version" android-ndk
        rm android-ndk.zip

        # The NDK toolchain file enforces `-g` as base C[XX] flag - remove it to
        # *significantly* reduce executable sizes
        toolchainFile="$PWD/android-ndk/build/cmake/android.toolchain.cmake"
        sed -i 's|^  -g$||' "$toolchainFile"

        arch='${{ inputs.arch }}'
        apiLevel='${{ inputs.android_api_level }}'
        if [[ "$arch" == armv7a ]]; then
          triple="$arch-linux-androideabi$apiLevel"
          cmakeFlags='-DANDROID_ABI=armeabi-v7a'
        elif [[ "$arch" == aarch64 ]]; then
          triple="$arch-linux-android$apiLevel"
          cmakeFlags='-DANDROID_ABI=arm64-v8a'
          cmakeFlags+=' -DLDC_INSTALL_LLVM_RUNTIME_LIBS_OS=android'
          cmakeFlags+=' -DLDC_INSTALL_LLVM_RUNTIME_LIBS_ARCH=aarch64-android'
        fi
        cmakeFlags+=" -DANDROID_NATIVE_API_LEVEL=$apiLevel"
        cmakeFlags+=" -DANDROID_STL=c++_static"
        cmakeFlags+=" -DCMAKE_TOOLCHAIN_FILE=$toolchainFile"
        cmakeFlags+=" -DD_LINKER_ARGS=-fuse-ld=bfd;-L$PWD/build-cross-libs/lib;-lphobos2-ldc;-ldruntime-ldc"

        echo "DFLAGS=-mtriple=$triple -fvisibility=hidden -L-L$PWD/build-cross-libs/lib -gcc=$PWD/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/$triple-clang" >> $GITHUB_ENV
        echo "CROSS_TRIPLE=$triple" >> $GITHUB_ENV
        echo "CROSS_CMAKE_FLAGS=$cmakeFlags" >> $GITHUB_ENV

    - name: Cross-compile default libraries
      shell: bash
      run: |
        set -eux
        cd ..
        IFS=$'\n' flags=( $(xargs -n1 <<<"$CROSS_CMAKE_FLAGS") )
        bootstrap-ldc/bin/ldc-build-runtime --ninja \
          --buildDir="build-cross-libs" \
          --dFlags="${DFLAGS// /;}" \
          --targetSystem='Android;Linux;UNIX' \
          --ldcSrcDir="$PWD/ldc" \
          "${flags[@]#-D}" # strip all `-D` prefixes

    - name: Cross-compile LDC executables
      shell: bash
      run: |
        set -eux
        cd ..
        # TODO: mimalloc
        installDir="$PWD/install"
        mkdir build-cross
        cd build-cross
        cmake -G Ninja ../ldc \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ROOT_DIR="$PWD/../llvm-cross" \
          -DD_COMPILER="$PWD/../bootstrap-ldc/bin/ldmd2" \
          -DCMAKE_INSTALL_PREFIX="$installDir" \
          -DINCLUDE_INSTALL_DIR="$installDir/import" \
          -DCMAKE_CROSSCOMPILING=True \
          $CROSS_CMAKE_FLAGS
        ninja ldc2 ldmd2 ldc-build-runtime ldc-profdata ldc-prune-cache
