name: 1-setup
runs:
  using: composite
  steps:
    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Install D host compiler
      uses: dlang-community/setup-dlang@v1.0.6
      with:
        compiler: ldc-latest
