name: Main
on: [push, pull_request]

env:
  CLANG_VERSION: 14.0.0
  LLVM_VERSION: 14.0.0

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: Linux x64
            os: ubuntu-18.04
            arch: x86_64
          - job_name: macOS x64
            os: macos-11
            arch: x86_64
          - job_name: Windows x64
            os: windows-2019
            arch: x64
          - job_name: Windows x86
            os: windows-2019
            arch: x86
    name: ${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 50
      - name: Setup
        uses: ./.github/actions/1-setup
        with:
          clang_version: ${{ env.CLANG_VERSION }}
          llvm_version: ${{ env.LLVM_VERSION }}
          arch: ${{ matrix.arch }}

  build-cross:
    name: Linux cross
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 50
      - name: Setup
        uses: ./.github/actions/1-setup
        with:
          clang_version: ${{ env.CLANG_VERSION }}
          llvm_version: ${{ env.LLVM_VERSION }}
          arch: x86_64
